[theme]
primaryColor = "#FF4B4B"  # Bright red for primary actions
backgroundColor = "#0E1117"  # Dark background
secondaryBackgroundColor = "#262730"  # Slightly lighter dark for cards/sections
textColor = "#FAFAFA"  # Almost white for text
font = "sans serif"

[server]
enableCORS = false
enableXsrfProtection = false

# Dark theme options
base = "dark"  # Set base theme to dark