[theme]
primaryColor = "#FF4B4B"
backgroundColor = "#0E1117"
secondaryBackgroundColor = "#262730"
textColor = "#FAFAFA"
font = "sans serif"

[server]
# Remove or comment out this line:
# base = "dark"  # This is not a valid option

# Other valid server options:
enableCORS = false
enableXsrfProtection = false